### PR TITLE
Create xzvibes.json

### PR DESCRIPTION
**Pull request by xzonix**

### CODE REVIEW

**Comment by xzonix** [comment]
Also, if it's possible, can some mantainer tell me how to make A records with the template?
Thanks!

**Comment by Joabutt** [comment]
the same way that you use it with CNAME, just change cname to A

**Comment by xzonix** [comment]
> the same way that you use it with CNAME, just change cname to A

So, another question: I have some A records on is-a.dev, can i just simply copy & paste them?

**Comment by xzonix** [comment]
So, is this JSON useful?:
{
  "owner": {
    "username": "xzonix",
    "email": "xz1@dr.com"
    "subdomain": "xzvibes"
  },
  "record": {
    "A": [
      "185.199.110.153",
      "185.199.108.153",
      "185.199.109.153",
      "185.199.111.153"
    ],
    "MX": [
      "mx1.improvmx.com",
      "mx2.improvmx.com"
    ],
    "TXT": "v=spf1 include:spf.improvmx.com ~all"
  }
}

**Comment by xzonix** [comment]
also if the PR is good just merge it

**Pull request merged**
