### PR TITLE
Create slime.json

### PR DESCRIPTION
**Pull request by purpleblueslime**

### CODE REVIEW

**Comment by purpleblueslime** [comment]
glitch not supported (?)

**Comment by Joabutt** [comment]
hi, you need to submit the pr before we can see :)

**Comment by purpleblueslime** [comment]
Alright, I've gone ahead already added `slime.is-really.cool` _in my glitch app_.

**Comment by Joabutt** [comment]
Hello, the Pr has mbeen merged and the site is up at https://slime.is-really.cool

**Pull request merged**
